using System;
using System.Linq;
//using System.Windows.Forms;
using System.Xml.Linq;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections;

namespace sat_ws
{
    class XMLConcentradoCFDINomina
    {
        //private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        /// <summary>
        /// Método encargado de Genenerar un XML para el cargado de CFDI de Nómina
        /// </summary>
        public static void CrearXMLConcentradoCFDINomina()
        {
            var RutaRelativaXML = "\\XMLConcentradoCFDINomina.xml";
            if (!File.Exists(RutaRelativaXML))
            {
                XDocument miXML = new XDocument(new XDeclaration("1.0", "utf-8", "yes"),
                    new XElement("CFDIXMLNOMINA"
                    ));
                miXML.Save(RutaRelativaXML);
            }
        }

        public static void EliminarXMLConcentradoCFDINomina()
        {
            var RutaRelativaXML = "\\XMLConcentradoCFDINomina.xml";
            if (File.Exists(RutaRelativaXML))
            {
                try
                {
                    File.Delete(RutaRelativaXML);
                }
                catch(Exception ex)
                {
                    //log.Error("Message: " + ex.Message + "######### StackTrace: " + ex.StackTrace.ToString());
                }                
            }
        }


        public static void AgregarCFDINominaXML12(CFDINomina CFDINominaDatos, Hashtable HTPercepciones, Hashtable HTDeducciones, XDocument xmlDoc, string version,  bool ValidaExistenciaCFDI)
        {
            
            try
            {            
                xmlDoc.Element("CFDIXMLNOMINA").Add(
                    new XElement("CFDI",
                    new XAttribute("EfectoComprobante", CFDINominaDatos.EfectoComprobante),
                    new XAttribute("Total", CFDINominaDatos.Total),
                    new XAttribute("SubTotal", CFDINominaDatos.SubTotal),
                    new XAttribute("FechaGeneracion", CFDINominaDatos.FechaGeneracion),
                    new XAttribute("Version", CFDINominaDatos.Version),
                    new XAttribute("Serie", CFDINominaDatos.Serie),
                    new XAttribute("Folio", CFDINominaDatos.Folio),
                    new XAttribute("LugarExpedicion", CFDINominaDatos.LugarExpedicion),
                    new XAttribute("MetodoPago", CFDINominaDatos.MetodoPago),
                    new XAttribute("FormaPago", CFDINominaDatos.FormaPago),
                    new XAttribute("Moneda", CFDINominaDatos.Moneda),
                    new XAttribute("NombreEmisor", CFDINominaDatos.NombreEmisor),
                    new XAttribute("RfcEmisor", CFDINominaDatos.RfcEmisor),
                    new XAttribute("RegimenFiscalEmsior", CFDINominaDatos.RegimenFiscalEmsior),
                    new XAttribute("NombreReceptor", CFDINominaDatos.NombreReceptor),
                    new XAttribute("RfcReceptor", CFDINominaDatos.RfcReceptor),
                    new XAttribute("UsoCFDI", CFDINominaDatos.UsoCFDI),
                    new XAttribute("TotalImpuestosTrasladados", CFDINominaDatos.TotalImpuestosRetenidos),
                    new XAttribute("TotalImpuestosRetenidos", CFDINominaDatos.TotalImpuestosRetenidos),
                    new XAttribute("Uuid", CFDINominaDatos.UUID),
                    new XAttribute("FechaTimbrado", CFDINominaDatos.FechaTimbrado),
                    new XAttribute("RfcProvCertif", CFDINominaDatos.RfcProvCertif),
                    new XAttribute("Nomina-TipoNomina", CFDINominaDatos.TipoNomina),
                    new XAttribute("Nomina-FechaPago", CFDINominaDatos.FechaPago),
                    new XAttribute("Nomina-FechaFinalPago", CFDINominaDatos.FechaFinalPago),
                    new XAttribute("Nomina-FechaInicialPago", CFDINominaDatos.FechaInicialPago),
                    new XAttribute("Nomina-NumDiasPagados", CFDINominaDatos.NumDiasPagados),
                    new XAttribute("Nomina-TotalPercepciones", CFDINominaDatos.TotalPercepciones),
                    new XAttribute("Nomina-TotalDeducciones", CFDINominaDatos.TotalDeducciones),

                    new XAttribute("Percepciones-TotalPercepcionesGravadas", CFDINominaDatos.TotalPercepcionesGravadas),
                    new XAttribute("Percepciones-TotalPercepcionesExentas", CFDINominaDatos.TotalPercepcionesExentas),   
                    new XAttribute("Percepciones-001-Gravadas", HTPercepciones["1-G"].ToString()),
                    new XAttribute("Percepciones-001-Exentas",  HTPercepciones["1-E"].ToString()),
                    new XAttribute("Percepciones-001-Totales",  HTPercepciones["1-T"].ToString()),
                    new XAttribute("Percepciones-002-Gravadas", HTPercepciones["2-G"].ToString()),
                    new XAttribute("Percepciones-002-Exentas",  HTPercepciones["2-E"].ToString()),
                    new XAttribute("Percepciones-002-Totales",  HTPercepciones["2-T"].ToString()),
                    new XAttribute("Percepciones-003-Gravadas", HTPercepciones["3-G"].ToString()),
                    new XAttribute("Percepciones-003-Exentas",  HTPercepciones["3-E"].ToString()),
                    new XAttribute("Percepciones-003-Totales",  HTPercepciones["3-T"].ToString()),
                    new XAttribute("Percepciones-004-Gravadas", HTPercepciones["4-G"].ToString()),
                    new XAttribute("Percepciones-004-Exentas",  HTPercepciones["4-E"].ToString()),
                    new XAttribute("Percepciones-004-Totales",  HTPercepciones["4-T"].ToString()),
                    new XAttribute("Percepciones-005-Gravadas", HTPercepciones["5-G"].ToString()),
                    new XAttribute("Percepciones-005-Exentas",  HTPercepciones["5-E"].ToString()),
                    new XAttribute("Percepciones-005-Totales",  HTPercepciones["5-T"].ToString()),
                    new XAttribute("Percepciones-006-Gravadas", HTPercepciones["6-G"].ToString()),
                    new XAttribute("Percepciones-006-Exentas",  HTPercepciones["6-E"].ToString()),
                    new XAttribute("Percepciones-006-Totales",  HTPercepciones["6-T"].ToString()),
                    new XAttribute("Percepciones-007-Gravadas", HTPercepciones["7-G"].ToString()),
                    new XAttribute("Percepciones-007-Exentas",  HTPercepciones["7-E"].ToString()),
                    new XAttribute("Percepciones-007-Totales",  HTPercepciones["7-T"].ToString()),
                    new XAttribute("Percepciones-008-Gravadas", HTPercepciones["8-G"].ToString()),
                    new XAttribute("Percepciones-008-Exentas",  HTPercepciones["8-E"].ToString()),
                    new XAttribute("Percepciones-008-Totales",  HTPercepciones["8-T"].ToString()),
                    new XAttribute("Percepciones-009-Gravadas", HTPercepciones["9-G"].ToString()),
                    new XAttribute("Percepciones-009-Exentas",  HTPercepciones["9-E"].ToString()),
                    new XAttribute("Percepciones-009-Totales",  HTPercepciones["9-T"].ToString()),
                    new XAttribute("Percepciones-010-Gravadas", HTPercepciones["10-G"].ToString()),
                    new XAttribute("Percepciones-010-Exentas",  HTPercepciones["10-E"].ToString()),
                    new XAttribute("Percepciones-010-Totales",  HTPercepciones["10-T"].ToString()),
                    new XAttribute("Percepciones-011-Gravadas", HTPercepciones["11-G"].ToString()),
                    new XAttribute("Percepciones-011-Exentas",  HTPercepciones["11-E"].ToString()),
                    new XAttribute("Percepciones-011-Totales",  HTPercepciones["11-T"].ToString()),
                    new XAttribute("Percepciones-012-Gravadas", HTPercepciones["12-G"].ToString()),
                    new XAttribute("Percepciones-012-Exentas",  HTPercepciones["12-E"].ToString()),
                    new XAttribute("Percepciones-012-Totales",  HTPercepciones["12-T"].ToString()),
                    new XAttribute("Percepciones-013-Gravadas", HTPercepciones["13-G"].ToString()),
                    new XAttribute("Percepciones-013-Exentas",  HTPercepciones["13-E"].ToString()),
                    new XAttribute("Percepciones-013-Totales",  HTPercepciones["13-T"].ToString()),
                    new XAttribute("Percepciones-014-Gravadas", HTPercepciones["14-G"].ToString()),
                    new XAttribute("Percepciones-014-Exentas",  HTPercepciones["14-E"].ToString()),
                    new XAttribute("Percepciones-014-Totales",  HTPercepciones["14-T"].ToString()),
                    new XAttribute("Percepciones-015-Gravadas", HTPercepciones["15-G"].ToString()),
                    new XAttribute("Percepciones-015-Exentas",  HTPercepciones["15-E"].ToString()),
                    new XAttribute("Percepciones-015-Totales",  HTPercepciones["15-T"].ToString()),
                    new XAttribute("Percepciones-016-Gravadas", HTPercepciones["16-G"].ToString()),
                    new XAttribute("Percepciones-016-Exentas",  HTPercepciones["16-E"].ToString()),
                    new XAttribute("Percepciones-016-Totales",  HTPercepciones["16-T"].ToString()),
                    new XAttribute("Percepciones-017-Gravadas", HTPercepciones["17-G"].ToString()),
                    new XAttribute("Percepciones-017-Exentas",  HTPercepciones["17-E"].ToString()),
                    new XAttribute("Percepciones-017-Totales",  HTPercepciones["17-T"].ToString()),
                    new XAttribute("Percepciones-018-Gravadas", HTPercepciones["18-G"].ToString()),
                    new XAttribute("Percepciones-018-Exentas",  HTPercepciones["18-E"].ToString()),
                    new XAttribute("Percepciones-018-Totales",  HTPercepciones["18-T"].ToString()),
                    new XAttribute("Percepciones-019-Gravadas", HTPercepciones["19-G"].ToString()),
                    new XAttribute("Percepciones-019-Exentas",  HTPercepciones["19-E"].ToString()),
                    new XAttribute("Percepciones-019-Totales",  HTPercepciones["19-T"].ToString()),
                    new XAttribute("Percepciones-020-Gravadas", HTPercepciones["20-G"].ToString()),
                    new XAttribute("Percepciones-020-Exentas",  HTPercepciones["20-E"].ToString()),
                    new XAttribute("Percepciones-020-Totales",  HTPercepciones["20-T"].ToString()),
                    new XAttribute("Percepciones-021-Gravadas", HTPercepciones["21-G"].ToString()),
                    new XAttribute("Percepciones-021-Exentas",  HTPercepciones["21-E"].ToString()),
                    new XAttribute("Percepciones-021-Totales",  HTPercepciones["21-T"].ToString()),
                    new XAttribute("Percepciones-022-Gravadas", HTPercepciones["22-G"].ToString()),
                    new XAttribute("Percepciones-022-Exentas",  HTPercepciones["22-E"].ToString()),
                    new XAttribute("Percepciones-022-Totales",  HTPercepciones["22-T"].ToString()),
                    new XAttribute("Percepciones-023-Gravadas", HTPercepciones["23-G"].ToString()),
                    new XAttribute("Percepciones-023-Exentas",  HTPercepciones["23-E"].ToString()),
                    new XAttribute("Percepciones-023-Totales",  HTPercepciones["23-T"].ToString()),
                    new XAttribute("Percepciones-024-Gravadas", HTPercepciones["24-G"].ToString()),
                    new XAttribute("Percepciones-024-Exentas",  HTPercepciones["24-E"].ToString()),
                    new XAttribute("Percepciones-024-Totales",  HTPercepciones["24-T"].ToString()),
                    new XAttribute("Percepciones-025-Gravadas", HTPercepciones["25-G"].ToString()),
                    new XAttribute("Percepciones-025-Exentas",  HTPercepciones["25-E"].ToString()),
                    new XAttribute("Percepciones-025-Totales",  HTPercepciones["25-T"].ToString()),
                    new XAttribute("Percepciones-026-Gravadas", HTPercepciones["26-G"].ToString()),
                    new XAttribute("Percepciones-026-Exentas",  HTPercepciones["26-E"].ToString()),
                    new XAttribute("Percepciones-026-Totales",  HTPercepciones["26-T"].ToString()),
                    new XAttribute("Percepciones-027-Gravadas", HTPercepciones["27-G"].ToString()),
                    new XAttribute("Percepciones-027-Exentas",  HTPercepciones["27-E"].ToString()),
                    new XAttribute("Percepciones-027-Totales",  HTPercepciones["27-T"].ToString()),
                    new XAttribute("Percepciones-028-Gravadas", HTPercepciones["28-G"].ToString()),
                    new XAttribute("Percepciones-028-Exentas",  HTPercepciones["28-E"].ToString()),
                    new XAttribute("Percepciones-028-Totales",  HTPercepciones["28-T"].ToString()),
                    new XAttribute("Percepciones-029-Gravadas", HTPercepciones["29-G"].ToString()),
                    new XAttribute("Percepciones-029-Exentas",  HTPercepciones["29-E"].ToString()),
                    new XAttribute("Percepciones-029-Totales",  HTPercepciones["29-T"].ToString()),
                    new XAttribute("Percepciones-030-Gravadas", HTPercepciones["30-G"].ToString()),
                    new XAttribute("Percepciones-030-Exentas",  HTPercepciones["30-E"].ToString()),
                    new XAttribute("Percepciones-030-Totales",  HTPercepciones["30-T"].ToString()),
                    new XAttribute("Percepciones-031-Gravadas", HTPercepciones["31-G"].ToString()),
                    new XAttribute("Percepciones-031-Exentas",  HTPercepciones["31-E"].ToString()),
                    new XAttribute("Percepciones-031-Totales",  HTPercepciones["31-T"].ToString()),
                    new XAttribute("Percepciones-032-Gravadas", HTPercepciones["32-G"].ToString()),
                    new XAttribute("Percepciones-032-Exentas",  HTPercepciones["32-E"].ToString()),
                    new XAttribute("Percepciones-032-Totales",  HTPercepciones["32-T"].ToString()),
                    new XAttribute("Percepciones-033-Gravadas", HTPercepciones["33-G"].ToString()),
                    new XAttribute("Percepciones-033-Exentas",  HTPercepciones["33-E"].ToString()),
                    new XAttribute("Percepciones-033-Totales",  HTPercepciones["33-T"].ToString()),
                    new XAttribute("Percepciones-034-Gravadas", HTPercepciones["34-G"].ToString()),
                    new XAttribute("Percepciones-034-Exentas",  HTPercepciones["34-E"].ToString()),
                    new XAttribute("Percepciones-034-Totales",  HTPercepciones["34-T"].ToString()),
                    new XAttribute("Percepciones-035-Gravadas", HTPercepciones["35-G"].ToString()),
                    new XAttribute("Percepciones-035-Exentas",  HTPercepciones["35-E"].ToString()),
                    new XAttribute("Percepciones-035-Totales",  HTPercepciones["35-T"].ToString()),
                    new XAttribute("Percepciones-036-Gravadas", HTPercepciones["36-G"].ToString()),
                    new XAttribute("Percepciones-036-Exentas",  HTPercepciones["36-E"].ToString()),
                    new XAttribute("Percepciones-036-Totales",  HTPercepciones["36-T"].ToString()),
                    new XAttribute("Percepciones-037-Gravadas", HTPercepciones["37-G"].ToString()),
                    new XAttribute("Percepciones-037-Exentas",  HTPercepciones["37-E"].ToString()),
                    new XAttribute("Percepciones-037-Totales",  HTPercepciones["37-T"].ToString()),
                    new XAttribute("Percepciones-038-Gravadas", HTPercepciones["38-G"].ToString()),
                    new XAttribute("Percepciones-038-Exentas",  HTPercepciones["38-E"].ToString()),
                    new XAttribute("Percepciones-038-Totales",  HTPercepciones["38-T"].ToString()),
                    new XAttribute("Percepciones-039-Gravadas", HTPercepciones["39-G"].ToString()),
                    new XAttribute("Percepciones-039-Exentas",  HTPercepciones["39-E"].ToString()),
                    new XAttribute("Percepciones-039-Totales",  HTPercepciones["39-T"].ToString()),    
                
                    new XAttribute("Deducciones-TotalDeduccionesImpuestosRetenidos", CFDINominaDatos.TotalDeduccionesImpuestosRetenidos),
                    new XAttribute("Deducciones-TotalDeduccionesOtrasDeducciones", CFDINominaDatos.TotalDeduccionesOtrasDeducciones),
                    new XAttribute("Deducciones-001", HTDeducciones["1"].ToString()),
                    new XAttribute("Deducciones-002", HTDeducciones["2"].ToString()),
                    new XAttribute("Deducciones-003", HTDeducciones["3"].ToString()),
                    new XAttribute("Deducciones-004", HTDeducciones["4"].ToString()),
                    new XAttribute("Deducciones-005", HTDeducciones["5"].ToString()),
                    new XAttribute("Deducciones-006", HTDeducciones["6"].ToString()),
                    new XAttribute("Deducciones-007", HTDeducciones["7"].ToString()),
                    new XAttribute("Deducciones-008", HTDeducciones["8"].ToString()),
                    new XAttribute("Deducciones-009", HTDeducciones["9"].ToString()),
                    new XAttribute("Deducciones-010", HTDeducciones["10"].ToString()),
                    new XAttribute("Deducciones-011", HTDeducciones["11"].ToString()),
                    new XAttribute("Deducciones-012", HTDeducciones["12"].ToString()),
                    new XAttribute("Deducciones-013", HTDeducciones["13"].ToString()),
                    new XAttribute("Deducciones-014", HTDeducciones["14"].ToString()),
                    new XAttribute("Deducciones-015", HTDeducciones["15"].ToString()),
                    new XAttribute("Deducciones-016", HTDeducciones["16"].ToString()),
                    new XAttribute("Deducciones-017", HTDeducciones["17"].ToString()),
                    new XAttribute("Deducciones-018", HTDeducciones["18"].ToString()),
                    new XAttribute("Deducciones-019", HTDeducciones["19"].ToString()),
                    new XAttribute("Deducciones-020", HTDeducciones["20"].ToString()),
                    new XAttribute("Deducciones-021", HTDeducciones["21"].ToString()),
                    new XAttribute("Receptor-Curp", CFDINominaDatos.Curp),
                    new XAttribute("Receptor-FechaInicioRelLaboral", CFDINominaDatos.FechaInicioRelLaboral),
                    new XAttribute("Receptor-Antigüedad", CFDINominaDatos.Antiguedad),
                    new XAttribute("Receptor-NumSeguridadSocial", CFDINominaDatos.NumSeguridadSocial),
                    new XAttribute("Receptor-TipoContrato", CFDINominaDatos.TipoContrato),
                    new XAttribute("Receptor-Sindicalizado", CFDINominaDatos.Sindicalizado),
                    new XAttribute("Receptor-TipoJornada", CFDINominaDatos.TipoJornada),
                    new XAttribute("Receptor-TipoRegimen", CFDINominaDatos.TipoRegimen),
                    new XAttribute("Receptor-NumeroEmpleado", CFDINominaDatos.NumeroEmpleado),
                    new XAttribute("Receptor-Departamento", CFDINominaDatos.Departamento),
                    new XAttribute("Receptor-Puesto", CFDINominaDatos.Puesto),
                    new XAttribute("Receptor-RiesgoPuesto", CFDINominaDatos.RiesgoPuesto),
                    new XAttribute("Receptor-PeriodicidadPago", CFDINominaDatos.PeriodicidadPago),
                    new XAttribute("Receptor-Banco", CFDINominaDatos.Banco),
                    new XAttribute("Receptor-Cuenta-Clabe-Bancaria", CFDINominaDatos.CuentaBancaria),
                    new XAttribute("Receptor-SalarioDiarioIntegrado", CFDINominaDatos.SalarioDiarioIntegrado),
                    new XAttribute("Receptor-ClaveEntFed", CFDINominaDatos.ClaveEntFed),
                    new XAttribute("HorasExtra-Dias", CFDINominaDatos.Dias),
                    new XAttribute("HorasExtra-TipoHoras", CFDINominaDatos.TipoHoras),
                    new XAttribute("HorasExtra-HorasExtra", CFDINominaDatos.HorasExtra),
                    new XAttribute("HorasExtra-ImportePagado", CFDINominaDatos.ImportePagado),
                    new XAttribute("Incapacidades-DiasIncapacidad", CFDINominaDatos.DiasIncapacidad),
                    new XAttribute("Incapacidades-TipoIncapacidad", CFDINominaDatos.TipoIncapacidad),
                    new XAttribute("Incapacidades-ImporteMonetario", CFDINominaDatos.ImporteMonetario),
                    new XAttribute("SeparacionIndemnizacion-TotalPagado", CFDINominaDatos.IndemnizacionTotalPagado),
                    new XAttribute("SeparacionIndemnizacion-NumAñosServicio", CFDINominaDatos.IndemnizacionNumAñosServicio),
                    new XAttribute("SeparacionIndemnizacion-UltimoSueldoMensOrd", CFDINominaDatos.IndemnizacionUltimoSueldoMensOrd),
                    new XAttribute("SeparacionIndemnizacion-IngresoAcumulable", CFDINominaDatos.IndemnizacionIngresoAcumulable),
                    new XAttribute("SeparacionIndemnizacion-IngresoNoAcumulable", CFDINominaDatos.IndemnizacionIngresoNoAcumulable),
                    new XAttribute("JubilacionPensionRetiro-TotalUnaExhibicion", CFDINominaDatos.JubilacionTotalUnaExhibicion),
                    new XAttribute("JubilacionPensionRetiro-TotalParcialidad", CFDINominaDatos.JubilacionTotalParcialidad),
                    new XAttribute("JubilacionPensionRetiro-MontoDiario", CFDINominaDatos.JubilacionMontoDiario),
                    new XAttribute("JubilacionPensionRetiro-IngresoAcumulable", CFDINominaDatos.JubilacionIngresoAcumulable),
                    new XAttribute("JubilacionPensionRetiro-IngresoNoAcumulable", CFDINominaDatos.JubilacionIngresoNoAcumulable),
                    new XAttribute("SubContratacion-IngresoAcumulable", CFDINominaDatos.RfcLabora),
                    new XAttribute("SubContratacion-PorcentajeTiempo", CFDINominaDatos.PorcentajeTiempo)                 
                )
                );
            }
            catch (Exception ex)
            {
                //log.Error("Message: " + ex.Message + "######### StackTrace: " + ex.StackTrace.ToString());
            }
        }

        public static void AgregarCFDINominaXML11(CFDINomina CFDINominaDatos, Hashtable HTPercepciones, Hashtable HTDeducciones, XDocument xmlDoc, string version, bool ValidaExistenciaCFDI)
        {
            
            try
            { 
                xmlDoc.Element("CFDIXMLNOMINA").Add(
                    new XElement("CFDI",
                    new XAttribute("EfectoComprobante", CFDINominaDatos.EfectoComprobante),
                    new XAttribute("Total", CFDINominaDatos.Total),
                    new XAttribute("SubTotal", CFDINominaDatos.SubTotal),
                    new XAttribute("FechaGeneracion", CFDINominaDatos.FechaGeneracion),
                    new XAttribute("Version", CFDINominaDatos.Version),
                    new XAttribute("Serie", CFDINominaDatos.Serie),
                    new XAttribute("Folio", CFDINominaDatos.Folio),
                    new XAttribute("LugarExpedicion", CFDINominaDatos.LugarExpedicion),
                    new XAttribute("MetodoDePago", CFDINominaDatos.MetodoPago),
                    new XAttribute("FormaDePago", CFDINominaDatos.FormaPago),
                    new XAttribute("Moneda", CFDINominaDatos.Moneda),
                    new XAttribute("NombreEmisor", CFDINominaDatos.NombreEmisor),
                    new XAttribute("RfcEmisor", CFDINominaDatos.RfcEmisor),
                    new XAttribute("RegimenFiscalEmsior", CFDINominaDatos.RegimenFiscalEmsior),
                    new XAttribute("NombreReceptor", CFDINominaDatos.NombreReceptor),
                    new XAttribute("RfcReceptor", CFDINominaDatos.RfcReceptor),
                    new XAttribute("UsoCFDI", CFDINominaDatos.UsoCFDI),
                    new XAttribute("TotalImpuestosTrasladados", CFDINominaDatos.TotalImpuestosRetenidos),
                    new XAttribute("TotalImpuestosRetenidos", CFDINominaDatos.TotalImpuestosRetenidos),
                    new XAttribute("Uuid", CFDINominaDatos.UUID),
                    new XAttribute("FechaTimbrado", CFDINominaDatos.FechaTimbrado),
                    new XAttribute("RfcProvCertif", CFDINominaDatos.RfcProvCertif),
                    new XAttribute("Nomina-TipoNomina", CFDINominaDatos.TipoNomina),
                    new XAttribute("Nomina-FechaPago", CFDINominaDatos.FechaPago),
                    new XAttribute("Nomina-FechaFinalPago", CFDINominaDatos.FechaFinalPago),
                    new XAttribute("Nomina-FechaInicialPago", CFDINominaDatos.FechaInicialPago),
                    new XAttribute("Nomina-NumDiasPagados", CFDINominaDatos.NumDiasPagados),
                    new XAttribute("Nomina-TotalPercepciones", CFDINominaDatos.TotalPercepciones),
                    new XAttribute("Nomina-TotalDeducciones", CFDINominaDatos.TotalDeducciones),

                    new XAttribute("Percepciones-TotalPercepcionesGravadas", CFDINominaDatos.TotalPercepcionesGravadas),
                    new XAttribute("Percepciones-TotalPercepcionesExentas", CFDINominaDatos.TotalPercepcionesExentas),
                    new XAttribute("Percepciones-001-Gravadas", HTPercepciones["1-G"].ToString()),
                    new XAttribute("Percepciones-001-Exentas", HTPercepciones["1-E"].ToString()),
                    new XAttribute("Percepciones-001-Totales", HTPercepciones["1-T"].ToString()),
                    new XAttribute("Percepciones-002-Gravadas", HTPercepciones["2-G"].ToString()),
                    new XAttribute("Percepciones-002-Exentas", HTPercepciones["2-E"].ToString()),
                    new XAttribute("Percepciones-002-Totales", HTPercepciones["2-T"].ToString()),
                    new XAttribute("Percepciones-003-Gravadas", HTPercepciones["3-G"].ToString()),
                    new XAttribute("Percepciones-003-Exentas", HTPercepciones["3-E"].ToString()),
                    new XAttribute("Percepciones-003-Totales", HTPercepciones["3-T"].ToString()),
                    new XAttribute("Percepciones-004-Gravadas", HTPercepciones["4-G"].ToString()),
                    new XAttribute("Percepciones-004-Exentas", HTPercepciones["4-E"].ToString()),
                    new XAttribute("Percepciones-004-Totales", HTPercepciones["4-T"].ToString()),
                    new XAttribute("Percepciones-005-Gravadas", HTPercepciones["5-G"].ToString()),
                    new XAttribute("Percepciones-005-Exentas", HTPercepciones["5-E"].ToString()),
                    new XAttribute("Percepciones-005-Totales", HTPercepciones["5-T"].ToString()),
                    new XAttribute("Percepciones-006-Gravadas", HTPercepciones["6-G"].ToString()),
                    new XAttribute("Percepciones-006-Exentas", HTPercepciones["6-E"].ToString()),
                    new XAttribute("Percepciones-006-Totales", HTPercepciones["6-T"].ToString()),
                    new XAttribute("Percepciones-007-Gravadas", HTPercepciones["7-G"].ToString()),
                    new XAttribute("Percepciones-007-Exentas", HTPercepciones["7-E"].ToString()),
                    new XAttribute("Percepciones-007-Totales", HTPercepciones["7-T"].ToString()),
                    new XAttribute("Percepciones-008-Gravadas", HTPercepciones["8-G"].ToString()),
                    new XAttribute("Percepciones-008-Exentas", HTPercepciones["8-E"].ToString()),
                    new XAttribute("Percepciones-008-Totales", HTPercepciones["8-T"].ToString()),
                    new XAttribute("Percepciones-009-Gravadas", HTPercepciones["9-G"].ToString()),
                    new XAttribute("Percepciones-009-Exentas", HTPercepciones["9-E"].ToString()),
                    new XAttribute("Percepciones-009-Totales", HTPercepciones["9-T"].ToString()),
                    new XAttribute("Percepciones-010-Gravadas", HTPercepciones["10-G"].ToString()),
                    new XAttribute("Percepciones-010-Exentas", HTPercepciones["10-E"].ToString()),
                    new XAttribute("Percepciones-010-Totales", HTPercepciones["10-T"].ToString()),
                    new XAttribute("Percepciones-011-Gravadas", HTPercepciones["11-G"].ToString()),
                    new XAttribute("Percepciones-011-Exentas", HTPercepciones["11-E"].ToString()),
                    new XAttribute("Percepciones-011-Totales", HTPercepciones["11-T"].ToString()),
                    new XAttribute("Percepciones-012-Gravadas", HTPercepciones["12-G"].ToString()),
                    new XAttribute("Percepciones-012-Exentas", HTPercepciones["12-E"].ToString()),
                    new XAttribute("Percepciones-012-Totales", HTPercepciones["12-T"].ToString()),
                    new XAttribute("Percepciones-013-Gravadas", HTPercepciones["13-G"].ToString()),
                    new XAttribute("Percepciones-013-Exentas", HTPercepciones["13-E"].ToString()),
                    new XAttribute("Percepciones-013-Totales", HTPercepciones["13-T"].ToString()),
                    new XAttribute("Percepciones-014-Gravadas", HTPercepciones["14-G"].ToString()),
                    new XAttribute("Percepciones-014-Exentas", HTPercepciones["14-E"].ToString()),
                    new XAttribute("Percepciones-014-Totales", HTPercepciones["14-T"].ToString()),
                    new XAttribute("Percepciones-015-Gravadas", HTPercepciones["15-G"].ToString()),
                    new XAttribute("Percepciones-015-Exentas", HTPercepciones["15-E"].ToString()),
                    new XAttribute("Percepciones-015-Totales", HTPercepciones["15-T"].ToString()),
                    new XAttribute("Percepciones-016-Gravadas", HTPercepciones["16-G"].ToString()),
                    new XAttribute("Percepciones-016-Exentas", HTPercepciones["16-E"].ToString()),
                    new XAttribute("Percepciones-016-Totales", HTPercepciones["16-T"].ToString()),
                    new XAttribute("Percepciones-017-Gravadas", HTPercepciones["17-G"].ToString()),
                    new XAttribute("Percepciones-017-Exentas", HTPercepciones["17-E"].ToString()),
                    new XAttribute("Percepciones-017-Totales", HTPercepciones["17-T"].ToString()),
                    new XAttribute("Percepciones-018-Gravadas", HTPercepciones["18-G"].ToString()),
                    new XAttribute("Percepciones-018-Exentas", HTPercepciones["18-E"].ToString()),
                    new XAttribute("Percepciones-018-Totales", HTPercepciones["18-T"].ToString()),
                    new XAttribute("Percepciones-019-Gravadas", HTPercepciones["19-G"].ToString()),
                    new XAttribute("Percepciones-019-Exentas", HTPercepciones["19-E"].ToString()),
                    new XAttribute("Percepciones-019-Totales", HTPercepciones["19-T"].ToString()),
                    new XAttribute("Percepciones-020-Gravadas", HTPercepciones["20-G"].ToString()),
                    new XAttribute("Percepciones-020-Exentas", HTPercepciones["20-E"].ToString()),
                    new XAttribute("Percepciones-020-Totales", HTPercepciones["20-T"].ToString()),
                    new XAttribute("Percepciones-021-Gravadas", HTPercepciones["21-G"].ToString()),
                    new XAttribute("Percepciones-021-Exentas", HTPercepciones["21-E"].ToString()),
                    new XAttribute("Percepciones-021-Totales", HTPercepciones["21-T"].ToString()),
                    new XAttribute("Percepciones-022-Gravadas", HTPercepciones["22-G"].ToString()),
                    new XAttribute("Percepciones-022-Exentas", HTPercepciones["22-E"].ToString()),
                    new XAttribute("Percepciones-022-Totales", HTPercepciones["22-T"].ToString()),
                    new XAttribute("Percepciones-023-Gravadas", HTPercepciones["23-G"].ToString()),
                    new XAttribute("Percepciones-023-Exentas", HTPercepciones["23-E"].ToString()),
                    new XAttribute("Percepciones-023-Totales", HTPercepciones["23-T"].ToString()),
                    new XAttribute("Percepciones-024-Gravadas", HTPercepciones["24-G"].ToString()),
                    new XAttribute("Percepciones-024-Exentas", HTPercepciones["24-E"].ToString()),
                    new XAttribute("Percepciones-024-Totales", HTPercepciones["24-T"].ToString()),
                    new XAttribute("Percepciones-025-Gravadas", HTPercepciones["25-G"].ToString()),
                    new XAttribute("Percepciones-025-Exentas", HTPercepciones["25-E"].ToString()),
                    new XAttribute("Percepciones-025-Totales", HTPercepciones["25-T"].ToString()),
                    new XAttribute("Percepciones-026-Gravadas", HTPercepciones["26-G"].ToString()),
                    new XAttribute("Percepciones-026-Exentas", HTPercepciones["26-E"].ToString()),
                    new XAttribute("Percepciones-026-Totales", HTPercepciones["26-T"].ToString()),
                    new XAttribute("Percepciones-027-Gravadas", HTPercepciones["27-G"].ToString()),
                    new XAttribute("Percepciones-027-Exentas", HTPercepciones["27-E"].ToString()),
                    new XAttribute("Percepciones-027-Totales", HTPercepciones["27-T"].ToString()),
                    new XAttribute("Percepciones-028-Gravadas", HTPercepciones["28-G"].ToString()),
                    new XAttribute("Percepciones-028-Exentas", HTPercepciones["28-E"].ToString()),
                    new XAttribute("Percepciones-028-Totales", HTPercepciones["28-T"].ToString()),
                    new XAttribute("Percepciones-029-Gravadas", HTPercepciones["29-G"].ToString()),
                    new XAttribute("Percepciones-029-Exentas", HTPercepciones["29-E"].ToString()),
                    new XAttribute("Percepciones-029-Totales", HTPercepciones["29-T"].ToString()),
                    new XAttribute("Percepciones-030-Gravadas", HTPercepciones["30-G"].ToString()),
                    new XAttribute("Percepciones-030-Exentas", HTPercepciones["30-E"].ToString()),
                    new XAttribute("Percepciones-030-Totales", HTPercepciones["30-T"].ToString()),
                    new XAttribute("Percepciones-031-Gravadas", HTPercepciones["31-G"].ToString()),
                    new XAttribute("Percepciones-031-Exentas", HTPercepciones["31-E"].ToString()),
                    new XAttribute("Percepciones-031-Totales", HTPercepciones["31-T"].ToString()),
                    new XAttribute("Percepciones-032-Gravadas", HTPercepciones["32-G"].ToString()),
                    new XAttribute("Percepciones-032-Exentas", HTPercepciones["32-E"].ToString()),
                    new XAttribute("Percepciones-032-Totales", HTPercepciones["32-T"].ToString()),
                    new XAttribute("Percepciones-033-Gravadas", HTPercepciones["33-G"].ToString()),
                    new XAttribute("Percepciones-033-Exentas", HTPercepciones["33-E"].ToString()),
                    new XAttribute("Percepciones-033-Totales", HTPercepciones["33-T"].ToString()),
                    new XAttribute("Percepciones-034-Gravadas", HTPercepciones["34-G"].ToString()),
                    new XAttribute("Percepciones-034-Exentas", HTPercepciones["34-E"].ToString()),
                    new XAttribute("Percepciones-034-Totales", HTPercepciones["34-T"].ToString()),
                    new XAttribute("Percepciones-035-Gravadas", HTPercepciones["35-G"].ToString()),
                    new XAttribute("Percepciones-035-Exentas", HTPercepciones["35-E"].ToString()),
                    new XAttribute("Percepciones-035-Totales", HTPercepciones["35-T"].ToString()),
                    new XAttribute("Percepciones-036-Gravadas", HTPercepciones["36-G"].ToString()),
                    new XAttribute("Percepciones-036-Exentas", HTPercepciones["36-E"].ToString()),
                    new XAttribute("Percepciones-036-Totales", HTPercepciones["36-T"].ToString()),
                    new XAttribute("Percepciones-037-Gravadas", HTPercepciones["37-G"].ToString()),
                    new XAttribute("Percepciones-037-Exentas", HTPercepciones["37-E"].ToString()),
                    new XAttribute("Percepciones-037-Totales", HTPercepciones["37-T"].ToString()),
                    new XAttribute("Percepciones-038-Gravadas", HTPercepciones["38-G"].ToString()),
                    new XAttribute("Percepciones-038-Exentas", HTPercepciones["38-E"].ToString()),
                    new XAttribute("Percepciones-038-Totales", HTPercepciones["38-T"].ToString()),
                    new XAttribute("Percepciones-039-Gravadas", HTPercepciones["39-G"].ToString()),
                    new XAttribute("Percepciones-039-Exentas", HTPercepciones["39-E"].ToString()),
                    new XAttribute("Percepciones-039-Totales", HTPercepciones["39-T"].ToString()),

                    new XAttribute("Deducciones-TotalGravado", CFDINominaDatos.TotalDeduccionesImpuestosRetenidos),
                    new XAttribute("Deducciones-TotalExento", CFDINominaDatos.TotalDeduccionesOtrasDeducciones),
                    new XAttribute("Deducciones-001-Gravadas", HTDeducciones["1-G"].ToString()),
                    new XAttribute("Deducciones-001-Exentas", HTDeducciones["1-E"].ToString()),
                    new XAttribute("Deducciones-001-Totales", HTDeducciones["1-T"].ToString()),
                    new XAttribute("Deducciones-002-Gravadas", HTDeducciones["2-G"].ToString()),
                    new XAttribute("Deducciones-002-Exentas", HTDeducciones["2-E"].ToString()),
                    new XAttribute("Deducciones-002-Totales", HTDeducciones["2-T"].ToString()),
                    new XAttribute("Deducciones-003-Gravadas", HTDeducciones["3-G"].ToString()),
                    new XAttribute("Deducciones-003-Exentas", HTDeducciones["3-E"].ToString()),
                    new XAttribute("Deducciones-003-Totales", HTDeducciones["3-T"].ToString()),
                    new XAttribute("Deducciones-004-Gravadas", HTDeducciones["4-G"].ToString()),
                    new XAttribute("Deducciones-004-Exentas", HTDeducciones["4-E"].ToString()),
                    new XAttribute("Deducciones-004-Totales", HTDeducciones["4-T"].ToString()),
                    new XAttribute("Deducciones-005-Gravadas", HTDeducciones["5-G"].ToString()),
                    new XAttribute("Deducciones-005-Exentas", HTDeducciones["5-E"].ToString()),
                    new XAttribute("Deducciones-005-Totales", HTDeducciones["5-T"].ToString()),
                    new XAttribute("Deducciones-006-Gravadas", HTDeducciones["6-G"].ToString()),
                    new XAttribute("Deducciones-006-Exentas", HTDeducciones["6-E"].ToString()),
                    new XAttribute("Deducciones-006-Totales", HTDeducciones["6-T"].ToString()),
                    new XAttribute("Deducciones-007-Gravadas", HTDeducciones["7-G"].ToString()),
                    new XAttribute("Deducciones-007-Exentas", HTDeducciones["7-E"].ToString()),
                    new XAttribute("Deducciones-007-Totales", HTDeducciones["7-T"].ToString()),
                    new XAttribute("Deducciones-008-Gravadas", HTDeducciones["8-G"].ToString()),
                    new XAttribute("Deducciones-008-Exentas", HTDeducciones["8-E"].ToString()),
                    new XAttribute("Deducciones-008-Totales", HTDeducciones["8-T"].ToString()),
                    new XAttribute("Deducciones-009-Gravadas", HTDeducciones["9-G"].ToString()),
                    new XAttribute("Deducciones-009-Exentas", HTDeducciones["9-E"].ToString()),
                    new XAttribute("Deducciones-009-Totales", HTDeducciones["9-T"].ToString()),
                    new XAttribute("Deducciones-010-Gravadas", HTDeducciones["10-G"].ToString()),
                    new XAttribute("Deducciones-010-Exentas", HTDeducciones["10-E"].ToString()),
                    new XAttribute("Deducciones-010-Totales", HTDeducciones["10-T"].ToString()),
                    new XAttribute("Deducciones-011-Gravadas", HTDeducciones["11-G"].ToString()),
                    new XAttribute("Deducciones-011-Exentas", HTDeducciones["11-E"].ToString()),
                    new XAttribute("Deducciones-011-Totales", HTDeducciones["11-T"].ToString()),
                    new XAttribute("Deducciones-012-Gravadas", HTDeducciones["12-G"].ToString()),
                    new XAttribute("Deducciones-012-Exentas", HTDeducciones["12-E"].ToString()),
                    new XAttribute("Deducciones-012-Totales", HTDeducciones["12-T"].ToString()),
                    new XAttribute("Deducciones-013-Gravadas", HTDeducciones["13-G"].ToString()),
                    new XAttribute("Deducciones-013-Exentas", HTDeducciones["13-E"].ToString()),
                    new XAttribute("Deducciones-013-Totales", HTDeducciones["13-T"].ToString()),
                    new XAttribute("Deducciones-014-Gravadas", HTDeducciones["14-G"].ToString()),
                    new XAttribute("Deducciones-014-Exentas", HTDeducciones["14-E"].ToString()),
                    new XAttribute("Deducciones-014-Totales", HTDeducciones["14-T"].ToString()),
                    new XAttribute("Deducciones-015-Gravadas", HTDeducciones["15-G"].ToString()),
                    new XAttribute("Deducciones-015-Exentas", HTDeducciones["15-E"].ToString()),
                    new XAttribute("Deducciones-015-Totales", HTDeducciones["15-T"].ToString()),
                    new XAttribute("Deducciones-016-Gravadas", HTDeducciones["16-G"].ToString()),
                    new XAttribute("Deducciones-016-Exentas", HTDeducciones["16-E"].ToString()),
                    new XAttribute("Deducciones-016-Totales", HTDeducciones["16-T"].ToString()),
                    new XAttribute("Deducciones-017-Gravadas", HTDeducciones["17-G"].ToString()),
                    new XAttribute("Deducciones-017-Exentas", HTDeducciones["17-E"].ToString()),
                    new XAttribute("Deducciones-017-Totales", HTDeducciones["17-T"].ToString()),
                    new XAttribute("Deducciones-018-Gravadas", HTDeducciones["18-G"].ToString()),
                    new XAttribute("Deducciones-018-Exentas", HTDeducciones["18-E"].ToString()),
                    new XAttribute("Deducciones-018-Totales", HTDeducciones["18-T"].ToString()),
                    new XAttribute("Deducciones-019-Gravadas", HTDeducciones["19-G"].ToString()),
                    new XAttribute("Deducciones-019-Exentas", HTDeducciones["19-E"].ToString()),
                    new XAttribute("Deducciones-019-Totales", HTDeducciones["19-T"].ToString()),
                    new XAttribute("Deducciones-020-Gravadas", HTDeducciones["20-G"].ToString()),
                    new XAttribute("Deducciones-020-Exentas", HTDeducciones["20-E"].ToString()),
                    new XAttribute("Deducciones-020-Totales", HTDeducciones["20-T"].ToString()),
                    new XAttribute("Deducciones-021-Gravadas", HTDeducciones["21-G"].ToString()),
                    new XAttribute("Deducciones-021-Exentas", HTDeducciones["21-E"].ToString()),
                    new XAttribute("Deducciones-021-Totales", HTDeducciones["21-T"].ToString()),

                    new XAttribute("Receptor-Curp", CFDINominaDatos.Curp),
                    new XAttribute("Receptor-FechaInicioRelLaboral", CFDINominaDatos.FechaInicioRelLaboral),
                    new XAttribute("Receptor-Antigüedad", CFDINominaDatos.Antiguedad),
                    new XAttribute("Receptor-NumSeguridadSocial", CFDINominaDatos.NumSeguridadSocial),
                    new XAttribute("Receptor-TipoContrato", CFDINominaDatos.TipoContrato),
                    new XAttribute("Receptor-Sindicalizado", CFDINominaDatos.Sindicalizado),
                    new XAttribute("Receptor-TipoJornada", CFDINominaDatos.TipoJornada),
                    new XAttribute("Receptor-TipoRegimen", CFDINominaDatos.TipoRegimen),
                    new XAttribute("Receptor-NumeroEmpleado", CFDINominaDatos.NumeroEmpleado),
                    new XAttribute("Receptor-Departamento", CFDINominaDatos.Departamento),
                    new XAttribute("Receptor-Puesto", CFDINominaDatos.Puesto),
                    new XAttribute("Receptor-RiesgoPuesto", CFDINominaDatos.RiesgoPuesto),
                    new XAttribute("Receptor-PeriodicidadPago", CFDINominaDatos.PeriodicidadPago),
                    new XAttribute("Receptor-Banco", CFDINominaDatos.Banco),
                    new XAttribute("Receptor-Cuenta-Clabe-Bancaria", CFDINominaDatos.CuentaBancaria),
                    new XAttribute("Receptor-SalarioDiarioIntegrado", CFDINominaDatos.SalarioDiarioIntegrado),
                    new XAttribute("Receptor-ClaveEntFed", CFDINominaDatos.ClaveEntFed),
                    new XAttribute("HorasExtra-Dias", CFDINominaDatos.Dias),
                    new XAttribute("HorasExtra-TipoHoras", CFDINominaDatos.TipoHoras),
                    new XAttribute("HorasExtra-HorasExtra", CFDINominaDatos.HorasExtra),
                    new XAttribute("HorasExtra-ImportePagado", CFDINominaDatos.ImportePagado),
                    new XAttribute("Incapacidades-DiasIncapacidad", CFDINominaDatos.DiasIncapacidad),
                    new XAttribute("Incapacidades-TipoIncapacidad", CFDINominaDatos.TipoIncapacidad),
                    new XAttribute("Incapacidades-ImporteMonetario", CFDINominaDatos.ImporteMonetario),
                    new XAttribute("SeparacionIndemnizacion-TotalPagado", CFDINominaDatos.IndemnizacionTotalPagado),
                    new XAttribute("SeparacionIndemnizacion-NumAñosServicio", CFDINominaDatos.IndemnizacionNumAñosServicio),
                    new XAttribute("SeparacionIndemnizacion-UltimoSueldoMensOrd", CFDINominaDatos.IndemnizacionUltimoSueldoMensOrd),
                    new XAttribute("SeparacionIndemnizacion-IngresoAcumulable", CFDINominaDatos.IndemnizacionIngresoAcumulable),
                    new XAttribute("SeparacionIndemnizacion-IngresoNoAcumulable", CFDINominaDatos.IndemnizacionIngresoNoAcumulable),
                    new XAttribute("JubilacionPensionRetiro-TotalUnaExhibicion", CFDINominaDatos.JubilacionTotalUnaExhibicion),
                    new XAttribute("JubilacionPensionRetiro-TotalParcialidad", CFDINominaDatos.JubilacionTotalParcialidad),
                    new XAttribute("JubilacionPensionRetiro-MontoDiario", CFDINominaDatos.JubilacionMontoDiario),
                    new XAttribute("JubilacionPensionRetiro-IngresoAcumulable", CFDINominaDatos.JubilacionIngresoAcumulable),
                    new XAttribute("JubilacionPensionRetiro-IngresoNoAcumulable", CFDINominaDatos.JubilacionIngresoNoAcumulable),
                    new XAttribute("SubContratacion-IngresoAcumulable", CFDINominaDatos.RfcLabora),
                    new XAttribute("SubContratacion-PorcentajeTiempo", CFDINominaDatos.PorcentajeTiempo)
                )
                );
            }
            catch (Exception ex)
            {
                //log.Error("Message: " + ex.Message + "######### StackTrace: " + ex.StackTrace.ToString());
            }
        }

        public static bool ExisteCFDNominaEnXML(string Uuid)
        {
            var RutaRelativaXML =  "\\XMLConcentradoCFDINomina.xml";
            XDocument xmlFile = XDocument.Load(RutaRelativaXML);

            var Consulta = from c in xmlFile.Elements("CFDIXMLNOMINA").Elements("CFDI")
                           select c;

            foreach (XElement Solicitud in Consulta)
            {
                var UuidEvaluar = Solicitud.Attribute("Uuid").Value;
                if (UuidEvaluar == Uuid)
                {
                    return true;
                }
            }
            return false;
        }
    }
}

