//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Auxiliares
    {
        public int id_auxiliar { get; set; }
        public string auxiliar { get; set; }
        public int tbc_lineas_produccion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
