//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Menus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbc_Menus()
        {
            this.tbc_Vistas = new HashSet<tbc_Vistas>();
        }
    
        public int id_menu { get; set; }
        public int id_menuPadre { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public bool isRaiz { get; set; }
        public bool isVisible { get; set; }
        public string pathDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbc_Vistas> tbc_Vistas { get; set; }
    }
}
