//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Usuarios
    {
        public int id_usuario { get; set; }
        public int id_rol { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public Nullable<System.DateTime> ultimo_movimiento { get; set; }
        public int id_estatus { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string telefono { get; set; }
        public string telefono_movil { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string correo_electronico { get; set; }
    
        public virtual tbc_Estatus tbc_Estatus { get; set; }
        public virtual tbc_Roles tbc_Roles { get; set; }
    }
}
