//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Contactos_Cliente
    {
        public int id_contacto_cliente { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario_creo { get; set; }
        public string tipo_contacto { get; set; }
        public string nombre_completo { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    }
}
