//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Uso_CFDI
    {
        public int id_uso_cfdi { get; set; }
        public string sigla { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> factor { get; set; }
    }
}
