//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Vistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbc_Vistas()
        {
            this.tbr_Rol_Vista = new HashSet<tbr_Rol_Vista>();
        }
    
        public int id_vista { get; set; }
        public int id_menu { get; set; }
        public string nombre { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public int id_estatus { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual tbc_Estatus tbc_Estatus { get; set; }
        public virtual tbc_Menus tbc_Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbr_Rol_Vista> tbr_Rol_Vista { get; set; }
    }
}
