//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Acciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbc_Acciones()
        {
            this.tbr_Rol_Vista_Accion = new HashSet<tbr_Rol_Vista_Accion>();
        }
    
        public int id_accion { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string fontAwesome { get; set; }
        public byte isVisible { get; set; }
        public int order_position { get; set; }
        public int id_estatus { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbr_Rol_Vista_Accion> tbr_Rol_Vista_Accion { get; set; }
    }
}
