//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Actividades_Calendario
    {
        public int id_actividad_calendario { get; set; }
        public int id_lineas_produccion { get; set; }
        public string actividad { get; set; }
        public int paso { get; set; }
        public string area { get; set; }
    }
}
