//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_RIF_Sectores
    {
        public int id_sector_tasa_iva { get; set; }
        public string actividad { get; set; }
        public decimal porcentaje_decimal { get; set; }
        public int porcentaje { get; set; }
    }
}
