//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Lineas_Produccion
    {
        public int tbc_lineas_produccion1 { get; set; }
        public string descripcion { get; set; }
        public string linea { get; set; }
        public string supervisor { get; set; }
    }
}
