//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Seguimiento_Cliente
    {
        public int id_seguimiento_cliente { get; set; }
        public string tipo { get; set; }
        public string motivo { get; set; }
        public string respuesta { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
    }
}
