//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_RIF_Tasa_ISR
    {
        public int id_tasa_isr { get; set; }
        public decimal limite_inferior { get; set; }
        public decimal limite_superior { get; set; }
        public decimal cuota_fija { get; set; }
        public decimal porcentaje_decimal { get; set; }
        public decimal porcentaje { get; set; }
        public int periodo { get; set; }
    }
}
