//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbc_Clientes
    {
        public int id_cliente { get; set; }
        public string nombre_razon { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_estatus { get; set; }
        public int id_tipo_persona { get; set; }
        public string direccion_fiscal { get; set; }
        public string rfc { get; set; }
        public int id_regimen { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> id_sector { get; set; }
        public Nullable<System.DateTime> fecha_servicio { get; set; }
        public Nullable<bool> ingresos_mayores { get; set; }
        public Nullable<bool> publico_general { get; set; }
        public Nullable<bool> estado_cuenta { get; set; }
        public Nullable<bool> tiene_trabajadores { get; set; }
        public string actividad_principal { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_caducidad_fiel { get; set; }
        public Nullable<bool> es_asesoria { get; set; }
        public Nullable<bool> aplica_coi { get; set; }
        public Nullable<bool> edo_financiero { get; set; }
        public Nullable<System.DateTime> fecha_cita { get; set; }
        public Nullable<System.DateTime> fecha_fiel_representante { get; set; }
        public Nullable<bool> es_nomina { get; set; }
        public Nullable<bool> registro_patronal { get; set; }
        public string patronal { get; set; }
        public Nullable<System.DateTime> inicio_razon { get; set; }
        public string clave_CIEC { get; set; }
    
        public virtual tbd_Ficha_Tecnica tbd_Ficha_Tecnica { get; set; }
    }
}
