//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Historial_Movimientos
    {
        public int id_historial_movimiento { get; set; }
        public int id_usuario { get; set; }
        public string movimiento { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
    }
}
