//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_RIF_ISR_Pagos
    {
        public int id_RIF_isr_pago { get; set; }
        public decimal isr { get; set; }
        public decimal recargo { get; set; }
        public decimal impuesto_actualizado { get; set; }
        public decimal total_pagar { get; set; }
        public int bimestre { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_recalculo { get; set; }
        public decimal monto_pago { get; set; }
        public int periodo { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario_creo { get; set; }
        public decimal diferencia { get; set; }
        public decimal importe { get; set; }
        public System.DateTime fecha_pago { get; set; }
    }
}
