//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Descargas_XML
    {
        public int id_descarga_xml { get; set; }
        public string rfc { get; set; }
        public int num_xml { get; set; }
        public string zip { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_procesado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public int xml_procesados { get; set; }
    }
}
