//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Depreciaciones
    {
        public int id_depreciacion { get; set; }
        public decimal saldo_inicial { get; set; }
        public int periodo { get; set; }
        public int id_uso_CFDI { get; set; }
        public int id_cliente { get; set; }
    }
}
