//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Actividades_Cliente
    {
        public int id_actividad_cliente { get; set; }
        public int id_cliente { get; set; }
        public decimal porcentaje { get; set; }
        public string actividad { get; set; }
        public int id_usuario_creo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
