//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Facturas
    {
        public int id_xml { get; set; }
        public string UUID { get; set; }
        public string RFCEmisor { get; set; }
        public string RFCReceptor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> impuesto_trasladado { get; set; }
        public Nullable<decimal> impuesto_retenido { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> forma_pago { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<System.DateTime> fecha_timbrado { get; set; }
        public string moneda { get; set; }
        public string nombre_emisor { get; set; }
        public string nombre_receptor { get; set; }
        public string url_xml { get; set; }
        public string version { get; set; }
        public string tipo { get; set; }
        public string folio { get; set; }
        public string usoCFDI { get; set; }
        public string tipo_comprobante { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string estatus { get; set; }
        public Nullable<decimal> ieps { get; set; }
        public Nullable<decimal> retencion_iva { get; set; }
        public Nullable<decimal> retencion_isr { get; set; }
        public Nullable<decimal> retencion_ieps { get; set; }
        public Nullable<decimal> retencion_local { get; set; }
        public Nullable<decimal> traslado_local { get; set; }
        public string cfdi_relacionados { get; set; }
        public string tipo_relacion_cfdi { get; set; }
        public string conceptos { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public Nullable<decimal> total_original { get; set; }
        public string serie { get; set; }
        public Nullable<decimal> isr_nomina { get; set; }
        public Nullable<decimal> subsidio_nomina { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> divisa { get; set; }
        public Nullable<System.DateTime> fecha_pago_p { get; set; }
        public string forma_pago_p { get; set; }
        public string moneda_p { get; set; }
        public string registropatronal { get; set; }
        public string tiponomina { get; set; }
        public Nullable<System.DateTime> fechapago { get; set; }
        public Nullable<System.DateTime> fechainicialpago { get; set; }
        public Nullable<System.DateTime> fechafinalpago { get; set; }
        public Nullable<decimal> numdiaspagados { get; set; }
        public Nullable<decimal> totalpercepciones { get; set; }
        public Nullable<decimal> totaldeducciones { get; set; }
        public Nullable<decimal> totalotrospagos { get; set; }
        public string curp { get; set; }
        public string numseguridadsocial { get; set; }
        public Nullable<System.DateTime> fechainiciorellaboral { get; set; }
        public string numempleado { get; set; }
        public string departamento { get; set; }
        public string puesto { get; set; }
        public string periodicidadpago { get; set; }
        public Nullable<decimal> salariobasecotapor { get; set; }
        public Nullable<decimal> salariodiariointegrado { get; set; }
        public Nullable<decimal> totalsueldos { get; set; }
        public Nullable<decimal> totalgravado { get; set; }
        public Nullable<decimal> totalexento { get; set; }
        public Nullable<decimal> totalotrasdeducciones { get; set; }
        public Nullable<decimal> totalimpuestosretenidos { get; set; }
        public Nullable<decimal> totalseparacionindemnizacionper { get; set; }
        public Nullable<decimal> totaljubilacionpensionretiroper { get; set; }
        public string estatus_aplicacion { get; set; }
        public Nullable<System.DateTime> fecha_validacion { get; set; }
        public Nullable<bool> EFOS { get; set; }
        public Nullable<decimal> sueldosGravado { get; set; }
        public Nullable<decimal> sueldosExento { get; set; }
        public Nullable<decimal> aguinaldoGravado { get; set; }
        public Nullable<decimal> aguinaldoExento { get; set; }
        public Nullable<decimal> primaDominicalGravado { get; set; }
        public Nullable<decimal> primaDominicalExento { get; set; }
        public Nullable<decimal> primaVacacionalGravado { get; set; }
        public Nullable<decimal> primaVacacionalExento { get; set; }
        public Nullable<decimal> primaAntiguedadGravado { get; set; }
        public Nullable<decimal> primaAntiguedadExento { get; set; }
        public Nullable<decimal> indemnizacionGravado { get; set; }
        public Nullable<decimal> indemnizacionExento { get; set; }
        public Nullable<decimal> subsidioCausado { get; set; }
        public Nullable<decimal> subsidioPagado { get; set; }
        public Nullable<decimal> C_seguroSocial { get; set; }
        public Nullable<decimal> C_isrDeduccion { get; set; }
        public Nullable<decimal> C_aportaciones { get; set; }
        public Nullable<decimal> C_infonavit { get; set; }
        public Nullable<decimal> ish { get; set; }
    }
}
