//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_XMLError
    {
        public int id_xml_error { get; set; }
        public int id_xml { get; set; }
        public string uuid { get; set; }
        public System.DateTime fecha_timbrado { get; set; }
        public string url_xml { get; set; }
        public string tipo { get; set; }
        public string rfc { get; set; }
    }
}
