//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Constancia_Sem_Cotizadas
    {
        public int id_solicitud { get; set; }
        public string curp { get; set; }
        public string nss { get; set; }
        public string correo { get; set; }
        public string url_documento { get; set; }
    }
}
