//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Notificaciones_Cliente
    {
        public int id_notificacion { get; set; }
        public string autoridad_emisora { get; set; }
        public string acto_administrativo { get; set; }
        public System.DateTime fecha_recepcion { get; set; }
        public System.DateTime fecha_notificacion { get; set; }
        public int mes { get; set; }
        public int periodo { get; set; }
        public string url_aviso_not { get; set; }
        public string url_acuse_not { get; set; }
        public string url_acto_not { get; set; }
        public int id_cliente { get; set; }
        public int es_anual { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
