//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Depositos
    {
        public int id_deposito { get; set; }
        public int periodo { get; set; }
        public int mes { get; set; }
        public decimal monto { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario_creo { get; set; }
        public Nullable<int> id_usuario_elimino { get; set; }
    }
}
