//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Certificado_Digital
    {
        public int id_solicitud { get; set; }
        public int id_tipo_persona { get; set; }
        public string url_tarjeta_patronal { get; set; }
        public string rfc { get; set; }
        public string usuario_imss { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string funcion_empresa { get; set; }
        public string url_identificacion { get; set; }
        public string url_comprobante { get; set; }
        public string url_certificado { get; set; }
        public string url_termino { get; set; }
        public string url_llave { get; set; }
    }
}
