//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Nomina_Factura
    {
        public int id_nomina_xml { get; set; }
        public string clave { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> importeexento { get; set; }
        public Nullable<decimal> importegravado { get; set; }
        public string tipopercepcion { get; set; }
        public string UUID { get; set; }
        public int id_xml { get; set; }
        public string registropatronal { get; set; }
        public string tiponomina { get; set; }
        public Nullable<System.DateTime> fechapago { get; set; }
        public Nullable<System.DateTime> fechainicialpago { get; set; }
        public Nullable<System.DateTime> fechafinalpago { get; set; }
        public Nullable<decimal> numdiaspagados { get; set; }
        public Nullable<decimal> totalpercepciones { get; set; }
        public Nullable<decimal> totaldeducciones { get; set; }
        public Nullable<decimal> totalotrospagos { get; set; }
        public string curp { get; set; }
        public string numseguridadsocial { get; set; }
        public Nullable<System.DateTime> fechainiciorellaboral { get; set; }
        public string numempleado { get; set; }
        public string departamento { get; set; }
        public string puesto { get; set; }
        public string periodicidadpago { get; set; }
        public Nullable<decimal> salariobasecotapor { get; set; }
        public Nullable<decimal> salariodiariointegrado { get; set; }
        public Nullable<decimal> totalsueldos { get; set; }
        public Nullable<decimal> totalgravado { get; set; }
        public Nullable<decimal> totalexento { get; set; }
        public Nullable<decimal> totalotrasdeducciones { get; set; }
        public Nullable<decimal> totalimpuestosretenidos { get; set; }
        public Nullable<decimal> totalseparacionindemnizacionper { get; set; }
        public Nullable<decimal> totaljubilacionpensionretiroper { get; set; }
    }
}
