//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Servicios_Cliente
    {
        public int id_servicio_cliente { get; set; }
        public int id_cliente { get; set; }
        public string servicio { get; set; }
        public int id_usuario_creo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> tbc_lineas_produccion { get; set; }
        public string encargado { get; set; }
        public Nullable<System.DateTime> inicio_servicio { get; set; }
        public Nullable<int> id_grupo_empresarial { get; set; }
    
        public virtual tbc_Grupo_Empresarial tbc_Grupo_Empresarial { get; set; }
    }
}
