//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Error_Lectura_XML
    {
        public int id_error_lectura_xml { get; set; }
        public string zip { get; set; }
        public string xml { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
