//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Conceptos_Factura
    {
        public int id_concepto_xml { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string claveprodserv { get; set; }
        public string claveunidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string unidad { get; set; }
        public Nullable<decimal> valorunitario { get; set; }
        public int id_xml { get; set; }
        public string UUID { get; set; }
        public Nullable<decimal> impuesto_trasladado { get; set; }
    }
}
