//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Entregables_Nomina_RFC
    {
        public int id_entregable_nomina_RFC { get; set; }
        public int periodo { get; set; }
        public int mes { get; set; }
        public int id_lista_entregable_nomina { get; set; }
        public string url_archivo { get; set; }
        public int id_usuario_creo { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public int id_cliente { get; set; }
        public string nombre_archivo { get; set; }
        public string observacion { get; set; }
        public string periodicidad { get; set; }
    }
}
