//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Ficha_Tecnica
    {
        public int id_cliente { get; set; }
        public string matriz { get; set; }
        public string sucursales { get; set; }
        public string representante { get; set; }
        public string objeto_social { get; set; }
        public string capital_inicial { get; set; }
        public string recomendacion { get; set; }
        public string humano { get; set; }
        public string inmobiliario { get; set; }
        public string equipo { get; set; }
        public string costos { get; set; }
        public string grupo { get; set; }
        public string canales { get; set; }
        public string alianzas { get; set; }
        public string observaciones { get; set; }
        public string prestamos { get; set; }
        public string politicas { get; set; }
        public string contratos { get; set; }
    
        public virtual tbc_Clientes tbc_Clientes { get; set; }
    }
}
