//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Estatus_XML
    {
        public int id_estatus_xml { get; set; }
        public int id_xml { get; set; }
        public string estatus { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    }
}
