//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Calendario_Produccion
    {
        public int id_calendario_produccion { get; set; }
        public int id_actividad_calendario { get; set; }
        public int mes { get; set; }
        public int periodo { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int avance { get; set; }
        public int id_usuario_creo { get; set; }
        public Nullable<System.DateTime> fecha_finalizado { get; set; }
    }
}
