//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbd_Cambio_Domicilio
    {
        public int id_solicitud { get; set; }
        public System.DateTime fecha_cambio { get; set; }
        public string calle { get; set; }
        public string codigo_postal { get; set; }
        public string num_ext { get; set; }
        public string num_int { get; set; }
        public string entre_calle { get; set; }
        public string y_calle { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string entidad_federativa { get; set; }
        public string tipo_inmueble { get; set; }
        public string tipo_calle { get; set; }
        public string caracteristicas_domicilio { get; set; }
        public string referencias_adicionales { get; set; }
        public string codigo_fiscal { get; set; }
        public string url_comprobante { get; set; }
        public string url_acuse_movimiento { get; set; }
    }
}
