//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imageapp.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbr_Rol_Vista_Accion
    {
        public int id_rol_vista_accion { get; set; }
        public int id_rol_vista { get; set; }
        public int id_accion { get; set; }
        public int id_permiso_servidor { get; set; }
    
        public virtual tbc_Acciones tbc_Acciones { get; set; }
        public virtual tbc_Permisos_Servidor tbc_Permisos_Servidor { get; set; }
        public virtual tbr_Rol_Vista tbr_Rol_Vista { get; set; }
    }
}
